import OpenAI from "openai";
import { Mistral } from "@mistralai/mistralai";
import dotenv from "dotenv";
import { MODELS } from "../config/open-router_models.js";

dotenv.config();


const openRouter = new OpenAI({

    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,

});


const groq = new OpenAI({

    baseURL: "https://api.groq.com/openai/v1",
    apiKey: process.env.GROQ_API_KEY,

});


const mistral = new Mistral({

    apiKey: process.env.MISTRAL_API_KEY,

});



export async function askCareerCompass(messages) {


    // -----------------------------
    // PRIMARY: Mistral
    // -----------------------------

    try {

        console.log("Trying Mistral API...");


        const response = await mistral.chat.complete({

            model: MODELS.PRIMARY,

            messages,

        });


        console.log(
            "Response generated by Mistral"
        );


        return {

            model: MODELS.PRIMARY,

            content:
                response.choices[0].message.content

        };


    } catch(error) {


        console.error(
            "Mistral failed:",
            error.message
        );

    }



    // -----------------------------
    // FALLBACK 1: Groq
    // -----------------------------

    try {


        console.log(
            "Trying Groq Llama..."
        );


        const response =
            await groq.chat.completions.create({

                model: MODELS.SECONDARY,

                messages,

            });



        console.log(
            "Response generated by Groq"
        );



        return {

            model: MODELS.SECONDARY,

            content:
                response.choices[0].message.content

        };


    } catch(error) {


        console.error(
            "Groq failed:",
            error.message
        );

    }




    // -----------------------------
    // FALLBACK 2: OpenRouter
    // -----------------------------

    try {


        console.log(
            "Trying OpenRouter..."
        );


        const response =
            await openRouter.chat.completions.create({

                model: MODELS.BACKUP,

                messages,

            });



        console.log(
            "Response generated by OpenRouter"
        );



        return {

            model: MODELS.BACKUP,

            content:
                response.choices[0].message.content

        };



    } catch(error) {


        console.error(
            "OpenRouter failed:",
            error.message
        );


        throw new Error(
            "All AI providers are unavailable."
        );

    }

}