import OpenAI from "openai";
import { Mistral } from "@mistralai/mistralai";
import dotenv from "dotenv";
import { MODELS } from "../config/open-router_models.js";

dotenv.config();

const openRouter = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,
});

const groq = new OpenAI({
    baseURL: "https://api.groq.com/openai/v1",
    apiKey: process.env.GROQ_API_KEY,
});

const mistral = new Mistral({
    apiKey: process.env.MISTRAL_API_KEY,
});


export async function askCareerCompass(messages) {

    // First attempt: Mistral API
    try {
        console.log("Trying Mistral API...");
        const response = await mistral.chat.complete({
            model: MODELS.PRIMARY,
            messages,
        });
        console.log("Response generated by: Mistral (mistral-small-latest)");
        return response.choices[0].message.content;

    } catch (error) {
        console.error("Mistral failed:", error.message);

        // Second attempt: Groq Llama 3.3 70B
        try {
            console.log("Trying Groq Llama 3.3 70B...");
            const response = await groq.chat.completions.create({
                model: MODELS.SECONDARY,
                messages,
            });
            console.log("Response generated by: Groq Llama 3.3 70B");
            return response.choices[0].message.content;

        } catch (error) {
            console.error("Groq Llama failed:", error.message);

            // Last resort: OpenRouter GPT-OSS 120B
            try {
                console.log("Trying OpenRouter GPT-OSS 120B...");
                const response = await openRouter.chat.completions.create({
                    model: MODELS.BACKUP,
                    messages,
                });
                console.log("Response generated by: OpenRouter GPT-OSS 120B");
                return response.choices[0].message.content;

            } catch (error) {
                console.error("OpenRouter GPT-OSS failed:", error.message);
                throw new Error("All AI providers are unavailable.");
            }
        }
    }
}
